name: production

on:
  push:
    branches: [master]
    path-ignore:
      - '.github/**'
  workflow_dispatch:
    inputs:
      ref:
        description: Commit SHA / branch to deploy
        default: master
        required: true

jobs:
  production:
    uses: ./.github/workflows/shared.yml
    with:
      cluster: apps
      environment: production
      subscription_id: 11001885-20be-4052-8647-9c6a919e3455 # Devolutions
      ref: ${{ inputs.ref }}
    secrets: inherit
